name: fasting_app
description: "A new Flutter project."

publish_to: "none"

version: 1.2.7+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  flutter_bloc: ^8.1.5
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3
  get_it: ^7.7.0
  fpdart: ^1.1.0
  funvas: ^0.1.8
  lottie: ^3.1.2
  rive: ^0.13.7
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^12.0.0
  permission_handler: ^11.3.1
  flutter_background_service: ^5.0.6
  soundpool: ^2.4.1
  share_plus: ^9.0.0
  sensors_plus: ^5.0.1
  restart_app: ^1.2.1
  upi_india: ^3.0.1
  package_info_plus: ^8.0.0
  vibration: ^1.9.0
  url_launcher: ^6.3.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  isar_generator: ^3.1.0+1
  analyzer: ^5.13.0
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/launcher_icon/stay fast.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/theme/
    - assets/lottie/
    - assets/launcher_icon/
    - assets/rive/
    - assets/images/
    - assets/sounds/
